name: Build Docker Container
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
 
        with:
          context: ./frontend.dockerfile
          run: |
          working-directory: flask-pytorch-backend/dockerfiles/frontend.dockerfile
          push: true
          tags: your-docker-repository:latest
