name: Demo

on:
  push:
    paths:
      - 'folder/**.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Update JSON Files
        run: ./path/to/binary/to/run/your/logic

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Changed JSON Files
